# Generated by Django 4.2.8 on 2023-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_lignecommande_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='prix_unitaire',
        ),
    ]
