# Generated by Django 4.2.8 on 2023-12-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_quantite'),
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournir_produit',
            name='fournisseur',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournir_produit',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournir_produit',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fournir_stock', to='stock.stock'),
            preserve_default=False,
        ),
    ]
