# Generated by Django 4.2.8 on 2023-12-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0002_fournir_produit_fournisseur_fournir_produit_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournir_produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur'),
        ),
    ]
