# Generated by Django 4.2.8 on 2023-12-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(help_text='La quantité en stock')),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_mouvement', models.CharField(choices=[('E', 'Entrée'), ('S', 'Sortie')], default='E', help_text='Type de mouvement (Entrée ou Sortie)', max_length=1)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
