# Generated by Django 4.2.8 on 2023-12-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='La quantité en stock')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
        migrations.AddField(
            model_name='stock',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
        ),
    ]
