# Generated by Django 4.2.8 on 2023-12-15 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_remove_produit_stock_delete_mouvementstock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'mouvement de stock', 'verbose_name_plural': 'mouvements de stock'},
        ),
        migrations.AddField(
            model_name='stock',
            name='date_mouvement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='type_mouvement',
            field=models.CharField(choices=[('E', 'Entrée'), ('S', 'Sortie')], default='E', help_text='Type de mouvement (Entrée ou Sortie)', max_length=1),
        ),
    ]
