# Generated by Django 4.2.8 on 2023-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_options_stock_date_mouvement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.IntegerField(default=0, help_text='La quantité en stock'),
        ),
    ]
